name: Xcode - Build IOS for Simulator

on:
  repository_dispatch:
    types: [trigger-action]
  workflow_dispatch:

jobs:
  build_app:
    name: Build and Zip App
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false

     #- name: Set up Node.js
        #uses: actions/setup-node@v3
        #with:
          #node-version: 18

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: _node_
          restore-keys: |
            _node_

      - name: Cache Specific CocoaPods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: _project_pods_
          restore-keys: |
            _project_pods_

      #- name: Install Node.js and Dependencies
        #uses: actions/setup-node@v3
        #with:
          #node-version: 18
      #- run: npm install

      #- name: Install CocoaPods Dependencies
        #run: |
          #cd ios
          #pod install

      - name: Cache iOS Build Folder
        uses: actions/cache@v2
        with:
          path: ios/build
          key: _ios_build_
          restore-keys: |
            _ios_build_

      - name: List files in (project)
        run: |
          echo "Listing files in the project dir:"
          ls -la

      - name: List files in (ios)
        run: |
          echo "Listing files in the ios dir:"
          ls -la ios

      - name: List files in (ios/build)
        run: |
          echo "Listing files in the build dir:"
          ls -la ios/build

      - name: Build App
        run: |
          cd ios
          xcodebuild -workspace 'MobleafExampleReact.xcworkspace' \
                      -scheme 'MobleafExampleReact' \
                      -sdk iphonesimulator \
                      -derivedDataPath 'build' \
                      -configuration Release \
                      -showBuildTimingSummary

      #- name: Zip .app file
      #run: |
      #cd ios/build/Build/Products/Release-iphonesimulator
      #zip -r MobleafExampleReact.app.zip .

      #- name: Upload App Artifact
      #uses: actions/upload-artifact@v4
      #with:
      #name: MobleafExample-app
      #path: ios/build/Build/Products/Release-iphonesimulator/MobleafExampleReact.app.zip

      #- name: Remove Zip File
      #run: |
      #rm ios/build/Build/Products/Release-iphonesimulator/MobleafExampleReact.app.zip
