name: Xcode - Build IOS for Simulator

on:
  repository_dispatch:
    types: [trigger-action]
  workflow_dispatch:

jobs:
  build_app:
    name: Build and Zip App
    runs-on: self-hosted

    steps:
      - name: Install Node.js dependencies
        run: |
          if [ -d "node_modules" ]; then
            echo "Node modules cache hit"
          else
            npm install
          fi

      - name: Install CocoaPods
        run: |
          if [ -d "ios/Pods" ]; then
            echo "CocoaPods cache hit"
          else
            cd ios && pod install
          fi
        
      - name: Build App
        run: |
          cd ios
          xcodebuild -workspace 'MobleafExampleReact.xcworkspace' \
              -scheme 'MobleafExampleReact' \
              -sdk iphonesimulator \
              -configuration Release \
              -derivedDataPath 'build' \
              -showBuildTimingSummary          

      #- name: Zip .app file
      #run: |
      #cd ios/build/Build/Products/Release-iphonesimulator
      #zip -r MobleafExampleReact.app.zip .

      #- name: Upload App Artifact
      #uses: actions/upload-artifact@v4
      #with:
      #name: MobleafExample-app
      #path: ios/build/Build/Products/Release-iphonesimulator/MobleafExampleReact.app.zip

      #- name: Remove Zip File
      #run: |
      #rm ios/build/Build/Products/Release-iphonesimulator/MobleafExampleReact.app.zip
