name: Xcode - Build IOS for Simulator

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  build_app:
    name: Build and Zip App
    runs-on: macos-13-xlarge
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js and Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - name: Cache Specific CocoaPods
        uses: actions/cache@v2
        id: cocoapods-cache
        with:
          path: |
            ios/Pods
          key: ${{ runner.os }}-specific-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-specific-pods-

      - name: Install CocoaPods Dependencies
        run: |
          cd ios
          pod install


      - name: Cache DerivedData
        uses: actions/cache@v2
        with:
          path: ios/build/Build/Products/Release-iphonesimulator
          key: ${{ runner.os }}-derivedData-${{ hashFiles('**/*.xcworkspace', '**/*.xcodeproj', '**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-derivedData-

      - name: Build App
        run: |
          cd ios
          xcodebuild -workspace 'MobleafExampleReact.xcworkspace' \
                      -scheme 'MobleafExampleReact' \
                      -sdk iphonesimulator \
                      -configuration Release \
                      -derivedDataPath './build' \
                      -showBuildTimingSummary \
                      -parallelizeTargets

      - name: Zip .app file
        run: |
          cd ios/build/Build/Products/Release-iphonesimulator
          zip -r MobleafExampleReact.app.zip MobleafExampleReact.app
          
      - name: Upload App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MobleafExample-app
          path: ios/build/Build/Products/Release-iphonesimulator/MobleafExample.app.zip

      - name: Remove Zip File
        run: |
          rm ios/build/Build/Products/Release-iphonesimulator/MobleafExampleReact.app.zip

