name: Xcode - Build IOS for Simulator

on:
  repository_dispatch:
    types: [trigger-action]
  workflow_dispatch:

jobs:
  build_app:
    name: Build and Zip App
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files in (project)
        run: ls -la

      - name: Cache (Derived Data)
        uses: actions/cache@v2
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: _derived_data_
          restore-keys: _derived_data_

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js and Dependencies
        with:
          node-version: 18
          run: |
            if [ -d "node_modules" ]; then
              echo "Node modules cache hit"
            else
              npm install
            fi

      - name: Cache CocoaPods pods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        run: |
          if [ -d "ios/Pods" ]; then
            echo "CocoaPods cache hit"
          else
            cd ios && pod install
          fi

      - name: List files in (ios)
        run: ls -la ios

      - name: Build App
        run: |
          cd ios
          xcodebuild -workspace 'MobleafExampleReact.xcworkspace' \
              -scheme 'MobleafExampleReact' \
              -sdk iphonesimulator \
              -configuration Release \
              -showBuildTimingSummary

      #- name: Zip .app file
      #run: |
      #cd ios/build/Build/Products/Release-iphonesimulator
      #zip -r MobleafExampleReact.app.zip .

      #- name: Upload App Artifact
      #uses: actions/upload-artifact@v4
      #with:
      #name: MobleafExample-app
      #path: ios/build/Build/Products/Release-iphonesimulator/MobleafExampleReact.app.zip

      #- name: Remove Zip File
      #run: |
      #rm ios/build/Build/Products/Release-iphonesimulator/MobleafExampleReact.app.zip
